### ISSUE TITLE
在华为HMA-AL00 android 10上录制短视频，报如下错误

### ISSUE THREAD

**Issue by hpdx** [SharryChoo/SAlbum#6]
I/IMediaRecorder: Record failed, errorCode is: -2
    java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.sharry.lib.media.recorder.H264Encoder.prepare(H264Encoder.java:57)
        at com.sharry.lib.media.recorder.VideoRecorder$1.run(VideoRecorder.java:125)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)

**Comment by hpdx** [comment]
原因我找到了，是视频帧的尺寸不合适导致的问题：
VideoRecorder类中的calculateRecordFrameSize方法，计算后得到视频帧的尺寸（int[] frameSize），在华为HMA-AL00 android 10上有问题。可以使用的几组值如下：

`frameSize[0] = 1080;
frameSize[1] = 1920；`

`frameSize[0] = 720;
frameSize[1] = 1080；`

`frameSize[0] = 720;
frameSize[1] = 960；`

这组是我在使用的，人物不会变胖、变形
`frameSize[0] = 924;
frameSize[1] =1920；`
